In [ ]:
#P1

#Code by Parthiv Abhani (1106)
!pip install tensorflow

import tensorflow as tf
from tensorflow import keras
import numpy as np

# Check TensorFlow version
print("TensorFlow Version:", tf.__version__)

# Create a Tensor
tensor = tf.constant([[1, 2], [3, 4]])
print("\nTensor:")
print(tensor)

# Build a Simple Neural Network
model = keras.Sequential([
    keras.layers.Input(shape=(4,)),
    keras.layers.Dense(8, activation="relu"),
    keras.layers.Dense(3, activation="softmax")
])

# Compile the Model
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Display Model Summary
model.summary()

# Create Dummy Data
X = np.random.rand(100, 4)
y = np.random.randint(0, 3, 100)

# Train the Model
model.fit(X, y, epochs=5, batch_size=16)

# Make Predictions
predictions = model.predict(X[:5])

print("\nPredictions:")
print(predictions)
print("\nPredicted Classes:")
print(np.argmax(predictions, axis=1))

TensorFlow Version: 2.20.0

Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.3600 - loss: 1.4466
Epoch 2/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3600 - loss: 1.3984  
Epoch 3/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3600 - loss: 1.3549 
Epoch 4/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3600 - loss: 1.3169 
Epoch 5/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3600 - loss: 1.2806
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Predictions:
[[0.6279027  0.07315026 0.298947  ]
 [0.6576878  0.15794875 0.18436348]
 [0.6251768  0.08512238 0.28970093]
 [0.60400176 0.14899674 0.24700156]
 [0.6768009  0.17584433 0.14735483]]

Predicted Classes:
[0 0 0 0 0]
